### ISSUE TITLE
Spam Score only shown in Mail, Column is Empty

### ISSUE THREAD

**Issue by Bommel24** [friedPotat0/Spam-Scores#1]
Title says it all. Thunderbird Version: 78.3.1 (32-Bit). My Spam Score is correctly shown when viewing an email, but it's not shown in the column. The relevant Header is "X-Spamd-Result".

**Comment by friedPotat0** [comment]
Thanks for reporting. It looks like `gDBView.getMsgHdrAt(row).getStringProperty('x-spamd-result')` is not returning the corresponding header value on some clients.

I will check for an alternative solution on how to parse the headers for the score column. Maybe it is possible to get the raw message like it is already done for the mail view itself.

**Comment by friedPotat0** [comment]
It should be fixed in the next version. You have to restart Thunderbird after the update and repair the folders you want the column to be displayed in.

**Comment by hackerscomputer** [comment]
Thunderbird 78.5.0 64 bit, Spam Score v 1.1.3 same problem, Spam Score and Report is correctly shown when viewing an email, but it's not shown in the column (show NaN ). The Header is "X-Server3-MailScanner-SpamCheck". 
Tryed with open email, restart and repair folder.
