### ISSUE TITLE
wrong rules report

### ISSUE THREAD

**Issue by hackerscomputer** [friedPotat0/Spam-Scores#11]
hello
find wrong score report in some mailscanner email, like this one with header attached below report wrong rule 47 with score 12....  seem get it form `X-AntiAbuse: Originator/Caller UID/GID - [47 12] / [47 12]` ?

X-AntiAbuse: This header was added to track abuse, please include it with any abuse report
X-AntiAbuse: Primary Hostname - xxxxxxxxxx.com
X-AntiAbuse: Original Domain - xxxxxxxxxx.com
X-AntiAbuse: Originator/Caller UID/GID - [47 12] / [47 12]
X-AntiAbuse: Sender Address Domain - xxxxxxxxxx.com
X-Get-Message-Sender-Via: xxxxxxxxxx.com: authenticated_id: xxxxxxxxxx.com
X-Authenticated-Sender: xxxxxxxxxx.com: xxxxxxxxxx.com
X-Source: 
X-Source-Args: 
X-Source-Dir: 
X-PlusHosting-MailScanner-Information: Please contact the ISP for more information
X-PlusHosting-MailScanner-ID: 1kkRY0-0002YS-Fx
X-PlusHosting-MailScanner-From: xxxxxxxxxx.com
X-Server3-MailScanner-Information: Please contact the ISP for more information
X-Server3-MailScanner-ID: 1kkRYg-0003QP-9c
X-Server3-MailScanner: Found to be clean
X-Server3-MailScanner-SpamCheck: non spam, SpamAssassin (not cached,
	punteggio=3.702, necessario 6, BAYES_50 0.80, DKIM_SIGNED 0.10,
	DKIM_VALID -0.10, DKIM_VALID_AU -0.10, DKIM_VALID_EF -0.10,
	HTML_IMAGE_RATIO_04 0.00, HTML_MESSAGE 0.00, KAM_SHORT 0.00,
	PYZOR_CHECK 0.70, SPF_PASS -0.00, ZZ_COUNTRY_WHITE 0.50,
	ZZ_RBL_BARRACU 1.90)
X-Server3-MailScanner-SpamScore: sss
X-Server3-MailScanner-From: xxxxxxxxxx.com
![spamscore](https://user-images.githubusercontent.com/26122222/100882771-d7d65080-34af-11eb-9dc7-c0199c24398e.jpg)

**Comment by friedPotat0** [comment]
Strange. I tested the header you provided, but the rule does not seem to show up. There has to be something else in the header causing the wrong rule.
![image](https://user-images.githubusercontent.com/5374007/100888446-6bab1b00-34b6-11eb-9272-da79668bac6d.png)

**Comment by hackerscomputer** [comment]
ok, i think becouse i'm manually install version 1.1.2 from mailscanner language branch ( v 1.1.2 ). now i update it to 1.1.4 and works ok, thanks

**Comment by friedPotat0** [comment]
Thanks for the explanation. I'm glad that everything works now.
