### ISSUE TITLE
Add support for X-Spam-Report header added by Exim

### ISSUE THREAD

**Issue by fuxii** [friedPotat0/Spam-Scores#12]
Would it be possible to add support for headers added by Exim? Since I'm not using rspamd in milter mode. Especially the detailed view with the used symbols would be the most interesting for me.

Example headers:

```
X-Spam-Status: No, score=1.9
X-Spam-Score: 1.9
X-Spam-Bar: +
X-Spam-Report: Action: no action
 Symbol: HAS_REPLYTO(0.00)
 Symbol: BAYES_SPAM(0.02)
 Symbol: FORWARDED(0.00)
 Symbol: IP_REPUTATION_HAM(-0.00)
 Symbol: R_SPF_ALLOW(0.00)
 Symbol: TO_DN_NONE(0.00)
 Symbol: DKIM_TRACE(0.00)
 Symbol: HAS_X_PRIO_THREE(0.00)
 Symbol: SUBJECT_ENDS_EXCLAIM(0.00)
 Symbol: FORGED_SENDER(0.00)
 Symbol: MIME_TRACE(0.00)
 Symbol: RCVD_TLS_LAST(0.00)
 Symbol: ASN(0.00)
 Symbol: FROM_NEQ_ENVFROM(0.00)
 Symbol: ARC_NA(0.00)
 Symbol: R_DKIM_ALLOW(0.00)
 Symbol: FROM_HAS_DN(0.00)
 Symbol: FORGED_SENDER_FORWARDING(0.00)
 Symbol: TO_MATCH_ENVRCPT_ALL(0.00)
 Symbol: URIBL_GREY(1.50)
 Symbol: REPLYTO_DOM_NEQ_FROM_DOM(0.00)
 Symbol: PREVIOUSLY_DELIVERED(0.00)
 Symbol: FORGED_SENDER_VERP_SRS(0.00)
 Symbol: RCPT_COUNT_ONE(0.00)
 Symbol: BAD_REP_POLICIES(0.10)
 Symbol: MANY_INVISIBLE_PARTS(0.05)
 Symbol: DMARC_NA(0.00)
 Symbol: MIME_HTML_ONLY(0.20)
 Symbol: RWL_MAILSPIKE_POSSIBLE(0.00)
 Symbol: RCVD_COUNT_TWO(0.00)
 Message-ID: xxx@xxx.net
X-Spam-Flag: NO
```

**Comment by friedPotat0** [comment]
Thanks for reporting! 
I've rewritten the symbol parsing in general now to support even prefixed score notations and limit the score parsing to the header itself. It should now support the header you provided.

You can test the new version before it will be released by follwing the instructions on the last paragraph of the installation section in the readme (https://github.com/friedPotat0/Spam-Scores#installation).

**Comment by fuxii** [comment]
Thanks for the fast reply. I tried your "change-symbol-parsing" branch and it works as expected now:

![spam-headers](https://user-images.githubusercontent.com/810572/103781303-710c0000-5036-11eb-8c81-3c23a5de488c.png)

Thanks again!

**Comment by friedPotat0** [comment]
The new version 1.1.5 is now released in the official Thunderbird's add-on store. I suggest you to uninstall the custom version you installed from the change-symbol-parsing branch and install it directly from the official page or the latest release of this GitHub repository (https://github.com/friedPotat0/Spam-Scores/releases/tag/1.1.5) in order to receive future updates.

Best regards and have a nice weekend.

**Comment by fuxii** [comment]
Thanks. My Thunderbird automatically updated to 1.1.5 from the repo. Thanks again for your fast resolution and effort!

**Comment by friedPotat0** [comment]
Oh, ok. That's good to know. Thanks for the feedback.

**Comment by fuxii** [comment]
I have to add here, that I clicked on "check for updates" on the addons page in Thunderbird. But then the addon was automatically updated ;)
