### ISSUE TITLE
Keine Anzeige von ScoreIcons in der Spam Score Spalte

### ISSUE THREAD

**Issue by andi6408** [friedPotat0/Spam-Scores#14]
Hallo, also auf diesem Wege, ich habe alles mehrfach wie  in der Anleitung beschrieben gemacht, es wird lediglich 1 Mail von tausenden mit einem Score angezeigt (Grün), alle anderen Mails sind leer? habe mehrere Rechner probiert, überall dasselbe? was tun?
![image](https://user-images.githubusercontent.com/77237035/104126171-61085f00-535b-11eb-8797-90ebe31ae0e7.png)

**Comment by friedPotat0** [comment]
Freut mich, dass es mit GitHub doch noch geklappt hat. Könnten Sie mir den Header von einer der Mails, bei denen die Score nicht ausgelesen werden kann, schicken. Dazu öffnen Sie eine der Mails ohne Score und klicken oben in der Aktionsleiste auf "Mehr" und dann "Quelltext anzeigen". Dort müssten irgendwo Abschnitte mit "X-Spamd-Result", "X-Spam-Report", "X-SpamCheck" oder "X-Spam-Status" stehen. Diese Teile bitte einfach hier posten. Dann schaue ich mir das Problem mal genauer an...

**Comment by andi6408** [comment]
danke für die Hilfe, kann im Quelltext aber nichts dergleichen finden?

**Comment by friedPotat0** [comment]
Dann hat die Mail auch keine Spam-Bewertung bekommen vom Mailserver. In diesem Fall können auch keine Bewertungen im Add-on angezeigt werden.

Darf ich fragen, um was für einen Mailserver es sich handelt? Ist dies ein öffentlicher von web, gmx oder gmail oder ein privater Mailserver? Bei öffentlichen Mailservern wird soweit ich weiß nur teilweise eine Score in den Header der empfangenen Mails geschrieben.

**Comment by andi6408** [comment]
Der Server ist von Globe.

**Comment by andi6408** [comment]
Und auch Gmx

**Comment by friedPotat0** [comment]
Also bei Globe weiß ich nicht, ob man den Spamfilter so konfigurieren kann, dass er die Scores zum Header hinzufügt. An dieser Stelle vielleicht einfach mal in die Mailserver-Konfiguration bei Globe schauen, was man so einstellen kann.

Bei GMX weiß ich, dass es solche Header gibt (siehe #8). Die GMX-Header haben nur das Problem, dass diese eine andere Skala verwenden, als alle Standard-Mailserver - nämlich nur positive Werte. Das wird zum aktuellen Zeitpunkt noch nicht vom Add-on unterstützt, da man in dem Zuge vermutlich noch einige andere eigene Mailserver-Abwandlungen unterstützen müsste.

**Comment by delzero** [comment]
Hi - I am guessing this issue is the same one I am getting - a blank column after trying all the tricks in the documentation to trigger the scores to appear. Are there any other steps I can take? or is this a bug or ?

Thanks.

**Comment by friedPotat0** [comment]
If there is no spam header in any of you mails, the score cannot be displayed. The add-on is just displaying the score written by your mail server to the header of the mails. One thing that currently does not work is the spam score of GMX headers. But the add-on is mostly aimed at SpamAssasin and Rspamd score headers, as the description states.

If you want, you can post one of your mail headers here (just blank out the IPs and mail adresses) and I can check if there is a score that should be displayed.

**Comment by delzero** [comment]
Hi! Thanks for the quick reply. I have two accounts, neither is working. One is 'Live' (i.e. microsoft). The other - I pasted a random header attached - Is that useful?

Just starting the journey of understanding this problem... Can your addin connect to a Windows installation of Spamassasin? Their FAQs say _'You therefore need to have an additional mail-routing program that is capable of using and interpreting the results from SpamAssassin, running in accordance with all defined procedures.'_

Thanks!
[sample email header20210128_153727.TXT](https://github.com/friedPotat0/Spam-Scores/files/5888356/sample.email.header20210128_153727.TXT)

**Comment by friedPotat0** [comment]
Thank you for posting the header. Unfortunately, there are no headers in the mail such as " X-Spamd-Result", "X-Spam-Report", "X-SpamCheck" or "X-Spam-Status".

Unless you have any custom mail server with SpamAssassin, MailScanner or RSpamd running or have at least a provider that adds such a header to the incoming mails, the add-on can't display anything useful for you. Sorry.

I should perhaps update the manual to make clear that the add-on cannot invent headers that do not exist. The add-on is mostly aimed at server admins or companies with own mail servers that want to quickly get an insight into their incoming score ratings.

**Comment by delzero** [comment]
Hi - Thanks for checking this out - Now I understand! It amazes me that the world still struggles iwth this... there isn't a global standard for every single email... 

There are so many systems at the various servers that seem to focus only on malware payloads (I have Avast on my PC that does this too). The Live account has an aggressive spam filter that I have to check the Junk folder often for 'real' emails... But my secondary account is not very advanced. I also know Thunderbird has a spam algorithm - but the user has to train it! (So far I've had zero success with that). And of course I could whitelist my known senders... 

I will look into the Windows Spamassasin to see if it can help at all...

**Comment by friedPotat0** [comment]
I can only agree with that. There are many solutions on the market that handle different scenarios of spam/ham ratings with varying degrees of success. In general, however, one can say that SpamAssasin and Rspamd are the most widely used services in the open-source world. Many of the big companies use spam scanners that are not very transparent to the user and lead to many false positives.

Therefore, I can only recommend to anyone who has a solid knowledge of unix server administration to run their own mail server and not leave the mail traffic to the commercial companies.

Closing this issue in favour of #8 for the GMX part.
