### ISSUE TITLE
Spam score not shown in Mail Collums

### ISSUE THREAD

**Issue by D1Ck3n** [friedPotat0/Spam-Scores#15]
Good day,

first of all: cool addon! i searched something like this a long time :)

but i got a issue:

![image](https://user-images.githubusercontent.com/28949322/106265232-0611ab80-6227-11eb-8a15-19bb7f349cc2.png)

Unfortunately, the spam score is not displayed next to my mails. Only when I open the mail can I see the score at the bottom. Is this a bug or do I have to do something special?

Thunderbird Version: 78.7.0 (64-bit)

**Comment by D1Ck3n** [comment]
okay, small update: it works in all folder except Inbox
![image](https://user-images.githubusercontent.com/28949322/106267011-5db11680-6229-11eb-9799-672c3d75cfa8.png)

**Comment by friedPotat0** [comment]
Have you already restarted Thunderbird and **then** repaired your inbox folder?

In case it still does not work, please provide an example of any of your mail headers from your inbox.

**Comment by D1Ck3n** [comment]
Hey @friedPotat0 
repair the inbox siced it! thanks! some mails are still missing a score but most of them get one :)

**Comment by friedPotat0** [comment]
I'm glad that it helped. The remaining mails certainly didn't get a spam header from the mail server. My own mail server, for example, does not add such headers when the mails are sent from one mailbox to another mailbox on the same mail server.
