### ISSUE TITLE
Problem displaying Score

### ISSUE THREAD

**Issue by CasperClous** [friedPotat0/Spam-Scores#16]
Hi, there is no display of the score at TB v78.7.0.
![image](https://user-images.githubusercontent.com/45837640/106772391-b95f1380-661e-11eb-951e-0f99fa213234.png)

**Comment by dragonxtek** [comment]
I am running Thunderbird 78.6.1 and I have the same issue. I enable the column to show the score, but it stills empty.
![Selection_029](https://user-images.githubusercontent.com/10552658/106771906-3f2e8f00-661e-11eb-90a0-4a7a783f90e0.png)

**Comment by friedPotat0** [comment]
I've tested the add-on in Thunderbird 78.7.0 which is currently the latest release. It works without any problems.

Did the add-on already work for you in a previous version, or are you using the add-on for the first time? In the second case, please provide an example of any header of a mail that does not show a score (just blank out any IP and mail addresses).

**Comment by CasperClous** [comment]
No, is the first time using it, and there is an Email from Twitter, that don't have a score.

![Untitled](https://user-images.githubusercontent.com/45837640/106790884-f3d2ab80-6632-11eb-9748-e385c67a5d39.png)

![image](https://user-images.githubusercontent.com/45837640/106791030-28defe00-6633-11eb-9cdc-c0f808bd59f5.png)

**Comment by friedPotat0** [comment]
Thank you for providing the header of the mail. Unfortunatelly this mail does not have any spam score header. I suspect that you don't have any custom mail server, but instead a public one from GMX, Gmail, ...

As I already described in the readme:

> The add-on needs mails with headers like "X-Spamd-Result", "X-Spam-Report", "X-SpamCheck" or "X-Spam-Status" to work. If a mail does not have one of these headers, it cannot display any spam score.

Unless you have any custom mail server with SpamAssassin, MailScanner or RSpamd running or have at least a provider that adds such a header to the incoming mails, the add-on can't display anything useful for you. Sorry.

**Comment by dragonxtek** [comment]
I have 2 mails. The first, with the following header, doesn't show the score :

> X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on mail-tester.com
X-Spam-Level:
X-Spam-Status: No/-0.2/5.0

And the second with the following headers shows the score:

> X-Spam-Checker-Version: SpamAssassin 3.2.5 (2008-06-10) on JetWeb
X-Spam-Level:
X-Spam-Status: No, score=-0.4 required=5.0 tests=ALL_TRUSTED,AWL,DKIM_SIGNED,

![Selection_037](https://user-images.githubusercontent.com/10552658/106802696-128c6e80-6642-11eb-8b98-6b12be248c0c.png)

Why the first one doesn't show the score? ¿Is it compatible with SpamAssassin 3.4.2?

**Comment by friedPotat0** [comment]
I've never seen this header variant of SpamAssassin before. Thank you for reporting. I will make an update as soon as possible to support this header.

**Comment by friedPotat0** [comment]
The header should be supported now. Please feel free to test it before it will be published. For installation refer to last paragraph of the installation section in the readme: https://github.com/friedPotat0/Spam-Scores#installation.

Use this branch for testing: https://github.com/friedPotat0/Spam-Scores/tree/spamassassin-score-variant

**Comment by dragonxtek** [comment]
Now it works! Thanks
![Selection_039](https://user-images.githubusercontent.com/10552658/106816282-ebd73380-6653-11eb-9d15-5e293ecb5f0b.png)

**Comment by friedPotat0** [comment]
No problem. I will do some more tests tomorrow and then submit this version to Thunderbird for review. Should be officially available in a few days.
