### ISSUE TITLE
Add option to show column icons and scores only for spams

### ISSUE THREAD

**Issue by sphh** [friedPotat0/Spam-Scores#20]
**Is your feature request related to a problem? Please describe.**
Personally when I am looking at the message list, I only want a quick overview, so I am only interested if an email was classified as spam, especially:
- I am not interested if it was not considered to be spam. Showing the green icons is distracting me from the important information, that the message might be spam (information overload …)
- and I am definitely not interested in the spam score. That's a detail I can investigate in the message pane, if I am thus inclined.

**Describe the solution you'd like**
1. I would like a column, showing only if a message is considered as spam, that is, it only shows the red icon, so that it clearly stands out.
2. I would like a column, which does not show the spam score.

I can think of two approaches:
1. Make the column configurable, so that you can select what is shown. I can think of those selectable options: Red icon, yellow icon, green icon, score as number.
2. Provide an additional column which only shows the red icon.

My preferred approach would be to have a second column, which is configurable. Why? If I look through my spam folder, I might want to se the spam score in the message list … So for me two different columns would be the best.

If the column width gets smaller, the header is truncated to e.g. `Spa…`. An icon would be appreciated here (TB already has one for its own `Junk Status` column).

**Describe alternatives you've considered**
I can "remove" the score by making the column so small, that just the icon is displayed. But I still get the green (and yellow) icons (and the column header now looks awful).

**Additional context**
The toolbar button in the message pane shows `Spam score: xxx`, which takes up quite a lot of space. Can this somehow be shortened? Maybe just show the (numerical) score? Because the tooltip carries the full name.

**Comment by friedPotat0** [comment]
I'll have to think about a proper solution for this. I could imagine a kind of minified version that you can activate in the settings. I think that a second column just for the minified version is too much work for this specific use case. 

I split the problem into another separate issue, which includes the idea of an icon as the column header.

**Comment by sphh** [comment]
I just re-evaluated my set up. The verdict is: I have two use cases in one TB instance:
1. On one of my mail boxes, I filter all possible spam into a separate mailbox.
2. For another mail box, I keep spam and incoming mail together in one mailbox.

For 2., I want only to see the icons, but for 1. I want to see all information in the spam mailbox; and just the yellow and red – if ever a possible spam mail strayed into my inbox – icons in my inbox. If we separate these two use cases, I would be happy with the following minimum behaviour:

- One column should do it.
- Option to not display the green (and maybe the yellow) icon, so that these messages stand out as a warning.
- I can make the column so small, that only the icon is shown and the score value disappears. But this would require #21.

So this simplifies to have a way to not show the green (or yellow) icon!

**Comment by friedPotat0** [comment]
The score ranges can now be displayed or hidden individually.

![image](https://user-images.githubusercontent.com/5374007/114289344-674fc980-9a77-11eb-96a2-573dbca356d7.png)

**Comment by sphh** [comment]
Thanks!

**Comment by sphh** [comment]
Just updated the add-on. It works perfectly!! Thanks again.
