### ISSUE TITLE
Add support for X-Rspamd-[...] headers

### ISSUE THREAD

**Issue by Starkstromkonsument** [friedPotat0/Spam-Scores#23]
**Is your feature request related to a problem? Please describe.**
The Servers of my hosting provider (https://uberspace.de/de/) only add spam-headers of the format:

```
X-Rspamd-Bar: /
X-Rspamd-Report: XM_UA_NO_VERSION(0.01) MIME_GOOD(-0.1) MIME_BASE64_TEXT(0.1) MISSING_TO(2) RCVD_NO_TLS_LAST(0.1) BAYES_HAM(-2.999991)
X-Rspamd-Score: -0.889991
```
or

```
X-Rspamd-Bar: ++++++++++++
X-Rspamd-Report: URI_COUNT_ODD(1) FUZZY_DENIED(10.348733) FROM_EXCESS_QP(1.2) RCVD_NO_TLS_LAST(0.1) R_MIXED_CHARSET(1.785714) BAYES_HAM(-2.999999) R_PARTS_DIFFER(0.790523) ONCE_RECEIVED(0.1) MIME_GOOD(-0.1) HAS_LIST_UNSUB(-0.01) BAD_REP_POLICIES(0.1)
X-Rspamd-Score: 12.314971
```

The add-on does not seem to recognize these. No Scores are shown.

**Describe the solution you'd like**
Add support for parsing these header fields in addition to X-Spam-[...]

**Comment by friedPotat0** [comment]
Should be working in the next version. I will submit this version to Mozilla for review this weekend and it should be available in Thunderbird next week.
