### ISSUE TITLE
Es werden nur bei älteren E-Mails vereinzelt Spam-Scores angezeigt

### ISSUE THREAD

**Issue by dan-dus** [friedPotat0/Spam-Scores#29]
Hi,

ich nutze Thunderbird 91.0.1 (64-Bit).

Mein Posteingang hat über 7000 E-Mails (IMAP).
Wenn ich den Posteingang anklicke und wie geschildert auf Eigenschaften und Reparieren klicke, erhalte erst mehrfach die Meldung, dass das Senden der E-Mail fehlgeschlagen und ist und wenn er durch ist, hat nur ein Bruchteil der E-Mails einen Spam-Score obwohl alle E-Mails einen haben.

Was mache ich falsch?

**Comment by friedPotat0** [comment]
> erhalte erst mehrfach die Meldung, dass das Senden der E-Mail fehlgeschlagen

Diese Meldung habe ich beim Reparieren eines Ordners noch nie gesehen. Da kann ich leider auch nicht helfen... sorry.

> hat nur ein Bruchteil der E-Mails einen Spam-Score obwohl alle E-Mails einen haben

Wäre es möglich einen Header einer Mail, bei der kein Spam-Score angezeigt wird, in anonymisierter Form hier zu posten? "nur bei älteren E-Mails vereinzelt Spam-Scores angezeigt" klingt irgendwie danach, dass sich irgendwas am Server seitdem geändert hat und evtl. andere Spam-Header hinzugefügt wurden, die von dem Add-On evtl. noch nicht unterstützt werden.

**Comment by dan-dus** [comment]
Ich kann dir das auch gerne mal zeigen (AnyDesk?).

Hier z.B Teile einer E-Mail von gestern. Ich habe einfach mal alles angefügt was "Spam" behinhaltet. Falls du mehr brauchst, tell me.

X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on
zensierte.domain.com
X-Spamd-Bar: +
Authentication-Results: mx.zensiertedomain.de;
	none
X-Rspamd-Queue-Id: 4GpzPK2jPfz5DjYD
X-Rspamd-Server: ker-l-mtasrv02p

Hier noch eine weitere

X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on
	zensierte.domain.com

Dann hier eine MIT Spam Score (3.04)

X-Spam-Checker-Version: SpamAssassin 3.4.2 (2018-09-13) on
	zensierte.domain.com

X-Spamd-Bar: +++
Authentication-Results: mx.zensiertedomain.de;
	none
X-Rspamd-Server: ker-l-mtasrv02p
X-Rspamd-Queue-Id: 49tGh90xpyz52M97
X-Spamd-Result: default: False [3.04 / 20.00];
	 ARC_NA(0.00)[];
	 FROM_HAS_DN(0.00)[];
	 MIME_GOOD(-0.10)[multipart/alternative,text/plain];
	 RCPT_COUNT_ONE(0.00)[1];
	 RCVD_COUNT_THREE(0.00)[4];
	 MANY_INVISIBLE_PARTS(1.00)[10];
	 DKIM_SIGNED(0.00)[];
	 TO_DN_ALL(0.00)[];
	 FROM_EQ_ENVFROM(0.00)[];
	 MIME_TRACE(0.00)[0:+,1:+,2:~];
	 RCVD_TLS_LAST(0.00)[];
	 FORGED_RECIPIENTS(2.00)[nichtantworten@zensiertedomain.de,0@d2.de ...];
	 R_PARTS_DIFFER(0.14)[56.8%];
	 TO_DOM_EQ_FROM_DOM(0.00)[]

P.S Finde deine Lösung super, wenn sie denn funktioniert.
Ich bin gerne behilflich.

**Comment by friedPotat0** [comment]
Vielen Dank für die Header...

Bei den ersten beiden Mails gibt es offensichtlich einfach keine Score, die angezeigt werden könnte. Lediglich die gekürzte Symbolform in der Form `X-Spamd-Bar: +` scheint vorhanden zu sein. Diese Form wird allerdings vom Add-on nicht ausgelesen, da diese ja nur die gerundete Bewertung angibt.

Die letzte Mail ist da schon was anderes. Da sind ja definitiv Werte und auch detailierte Spam-Regeln aufgelistet im Header. Auffällig ist allerdings die Leerzeile nach der `X-Spam-Checker-Version`. Ist die wirklich in dieser Form im Header der Mail vorhanden? Laut RFC-Standard wird der Header einer Mail nämlich mit einer leeren Zeile abgeschlossen und die nachfolgenden Zeilen bilden den Body der Mail. Das wird dann auch der Grund sein warum das Add-on die Score nicht auslesen kann. Der halbe Header wird schlichtweg einfach nicht als Header erkannt.

So etwas habe ich von SpamAssassin allerdings bisher auch noch nicht gesehen. Mir fällt auch aktuell keine Möglichkeit ein das Problem zu beheben...

**Comment by dan-dus** [comment]
> 
> 
> Vielen Dank für die Header...
> 
> Bei den ersten beiden Mails gibt es offensichtlich einfach keine Score, die angezeigt werden könnte. Lediglich die gekürzte Symbolform in der Form `X-Spamd-Bar: +` scheint vorhanden zu sein. Diese Form wird allerdings vom Add-on nicht ausgelesen, da diese ja nur die gerundete Bewertung angibt.
> 

Ja in der Tat haben die meisten keinen Score. Ist mir dann auch aufgefallen. Liegt das an meinem E-Mail-Anbieter? Oder an irgendeiner Einstellung?

> Die letzte Mail ist da schon was anderes. Da sind ja definitiv Werte und auch detailierte Spam-Regeln aufgelistet im Header. Auffällig ist allerdings die Leerzeile nach der `X-Spam-Checker-Version`. Ist die wirklich in dieser Form im Header der Mail vorhanden? Laut RFC-Standard wird der Header einer Mail nämlich mit einer leeren Zeile abgeschlossen und die nachfolgenden Zeilen bilden den Body der Mail. Das wird dann auch der Grund sein warum das Add-on die Score nicht auslesen kann. Der halbe Header wird schlichtweg einfach nicht als Header erkannt.
> 

Entschuldige bitte, da haben wir uns missverstanden. Bei dieser E-Mail wird der Spam Score korrekt angezeigt. Aber ist halt einer der wenigen E-Mails.

> So etwas habe ich von SpamAssassin allerdings bisher auch noch nicht gesehen. Mir fällt auch aktuell keine Möglichkeit ein das Problem zu beheben...

**Comment by friedPotat0** [comment]
Ah okay. Also dass die meisten Mails keinen richtigen Score in den Header enthalten ist eine Einstellung des E-Mail-Anbieters. Je nach Anbieter könnte man dort evtl. mal nachfragen. Serverseitig muss SpamAssassin so konfiguriert werden, dass der entsprechende Score-Header und im besten Fall auch die Einzelregeln bei eingehenden Mails in den Header geschrieben werden.
