### ISSUE TITLE
Popup and settings don't consider themes

### ISSUE THREAD

**Issue by henkelmax** [friedPotat0/Spam-Scores#3]
The spam score popup and the settings screen don't consider the theme.

![image](https://user-images.githubusercontent.com/13237524/95195178-7b6bf300-07d6-11eb-83d5-6b2f71eb0598.png)
![image](https://user-images.githubusercontent.com/13237524/95195264-98a0c180-07d6-11eb-9ab7-d8b0886ac6a0.png)

**Comment by friedPotat0** [comment]
It looks like the white background colour is set outside of the shadow root containing the add-on settings.

One workaround could be to implement a dark mode specifically for this add-on. But I don't know if there are multiple dark theme color variants to consider when implementing such a feature.

I will look into this in more detail soon.

**Comment by jdreesen** [comment]
I'm using the dark theme and the popup is unreadable for me:

![grafik](https://user-images.githubusercontent.com/424602/113478556-d16dda80-9489-11eb-90ff-14daf0ccf96b.png)

**Comment by friedPotat0** [comment]
Are you using any specific dark theme or the one from Mozilla? I've tested the official dark mode theme of Mozilla and it looks like in the screenshot of @henkelmax.

Sadly I have still not figured out how to adjust the layout of the popup and the settings pane according to the selected dark or light theme. Any ideas or hints on how to make this possible for Thunderbird's MailExtensions are appreciated.

**Comment by jdreesen** [comment]
I'm using Windows 10 in dark mode and the default thunderbird theme:

![grafik](https://user-images.githubusercontent.com/424602/113508758-14938080-9552-11eb-88fc-4fbbb6c370e8.png)

Additionally, I've [Dark Reader](https://addons.thunderbird.net/de/thunderbird/addon/darkreader/) installed but I don't think it influences the UI/chrome (and the popup doesn't change when I disable Dark Reader).

I think I've changed some colors in the settings a bit (not sure what the defaults are anymore, and it was before using Dark Reader which changes them too, I think):

![grafik](https://user-images.githubusercontent.com/424602/113508894-d9458180-9552-11eb-9ddb-16953baa761c.png)

---

> Sadly I have still not figured out how to adjust the layout of the popup and the settings pane according to the selected dark or light theme. Any ideas or hints on how to make this possible for Thunderbird's MailExtensions are appreciated.

I'm sorry, I have absolutely no experience in developing Thunderbird addons :/

**Comment by friedPotat0** [comment]
Ok, thanks for the information. It seems like the overridden text color has caused the font in the popup to be displayed like that. I've set the font color to black as long as I've not managed to figure out how to properly consider dark themes in general.

The fix will be included in the next update which I'm going to publish in the next couple of days.

**Comment by friedPotat0** [comment]
![image](https://user-images.githubusercontent.com/5374007/113611725-36266200-964f-11eb-92a2-984c600941ba.png)
![image](https://user-images.githubusercontent.com/5374007/113611781-48a09b80-964f-11eb-9485-cd9ae2cdb3c3.png)

**Comment by friedPotat0** [comment]
The dark mode will be fully supported in the next add-on version. (fixed in 7adf1034f2c6da8ec4726bdf7e92354ca5c884a6)
