### ISSUE TITLE
Score icon ranges resetting after restart

### ISSUE THREAD

**Issue by henkelmax** [friedPotat0/Spam-Scores#4]
The score icon ranges are resetting to the default values after restarting thunderbird.
After clicking at the options tab of the addon, the icons are back to the values provided in the settings.

**Comment by friedPotat0** [comment]
One thing that is difficult to test during development because every time you restart Thunderbird when debugging an add-on, it removes the add-on completely. So thanks for reporting!

It should be fixed in the next version...

**Comment by henkelmax** [comment]
Still not working in 1.1.1
