### ISSUE TITLE
Thunderbird 102: Column disappears after restart

### ISSUE THREAD

**Issue by d4k0** [friedPotat0/Spam-Scores#51]
Hello,

after the initial setup Spam Score works without any problems:

![SpamScores_1](https://user-images.githubusercontent.com/10982825/177852858-a3fe345a-1c9a-4d6a-a2ca-d9900bf92c12.png)

However, after restarting Thunderbird, the column disappears and you cannot select it again at first:

![SpamScores_2](https://user-images.githubusercontent.com/10982825/177852860-84007f83-e91f-4b61-b86a-1c458111b366.png)

You have to go to another folder and go back to the desired folder for Spam Score to show up again in the selection of columns:

![SpamScores_3](https://user-images.githubusercontent.com/10982825/177852864-3ed12236-15aa-4ff3-8cd3-02857ae59779.png)

I have tested this with a new profile. I've only been using Spam Score since Thunderbird 102, so I don't know if the problem was there before. However, there seems to be a similar problem with Send Later.

Apparently the Thunderbird developers wanted to change something about the startup behavior of add-ons, but I don't know if that was fully implemented (probably not according to an older comment from the Send Later developer).

**Comment by friedPotat0** [comment]
Thank you for the feedback. I noticed a couple of weeks ago that the column sometimes suddenly disappeared. I thought that it was a local problem with my Thunderbird installation. This often happens during debugging and development and it's always difficult for me to say whether it's the same for other users.

I will have a look at this in the next days and see if I can find a solution.

**Comment by d4k0** [comment]
Thanks for the confirmation!

**Comment by friedPotat0** [comment]
Seems to be working now. You can try it out by opening the Add-ons Manager (Tools -> Add-ons and Themes) and then drag & drop the following file: [spam_scores-1.4.0-tb.zip](https://github.com/friedPotat0/Spam-Scores/files/9067577/spam_scores-1.4.0-tb.zip)

Please let me know if the fix solves the issue on your side. I will have a look at the other open bug reports and then try to publish this fix as soon as possible.

**Comment by d4k0** [comment]
Thanks, this fixes the problem!

**Comment by dtill** [comment]
amazing!! the above .zip-version fixed it also on my side on both configurations:

- macOS Big Sur (11.6.7) and macOS Monterey (12.4)
- Thunderbird Version: 102.0.1 (64-Bit)
