### ISSUE TITLE
All email Vanished

### ISSUE THREAD

**Issue by deanland** [friedPotat0/Spam-Scores#66]
**Ran the app. Then all the email in that folder VANISHED.

**Reproduction steps**
**Here is exactly what I did, as suggested in the pop-up after downloading/installing it**:
                    Restart Thunderbird.
                    Right-click on a folder and select "Properties".
                    Click on "Repair Folder"

**Expected behavior**
**I  expected it to SCORE any spam, and offer a spam score for the folder,**

**Screenshots**

**Thunderbird (please complete the following information):**
 - OS: **Windows 11**
 - Version: **Thunderbird 115.14.0 (64 bit)**

**Spam Score add-on (please complete the following information):**
 - Version:  **1.5.0**

**Additional context**
Add any other context about the problem here. If, for example, no spam score is visible in the list view column, please provide an example of a header of any of these mails (blank out private information like IP or mail addresses). CAN'T DO THAT - EVERYTHING IS GONE.  OBVIOUSLY I AM RELUCTANT (to put it mildly) TO RUN IT ON ANY OTHE FOLDERS.

And the killer note: this was on my main inbox.  No inbound mail has come in since. But there is new mail, seen on my server, available via webmail. So has Spam Score locked out email reception??

**Comment by friedPotat0** [comment]
First of all, I'm very sorry to hear that. However, the add-on has nothing directly to do with any missing mails after repairing the Inbox folder in Thunderbird. Repairing the folders only causes Thunderbird to rewrite the summary file (*.msf) for the respective folder. Messages that no longer exist on the mail server but are still displayed in Thunderbird are removed from this file. If the mails are still present in the web mailbox, then there appears to be an error with the local MSF files. It may help to press Repair again or delete the files manually in the Profiles folder or reinstall Thunderbird.

I would like to point out that I do not take any liability for lost data when applying these steps. As I said: The repair step is only a local synchronisation of the mails with the online mailbox by Thunderbird and has nothing to do with the add-on itself.

Firstly, I would check whether the mails are still visible online and then look for a suitable solution in Thunderbird to fix the incorrect displaying status.
