### ISSUE TITLE
Details View is empty but Columns are working correctly

### ISSUE THREAD

**Issue by bephinix** [friedPotat0/Spam-Scores#67]
**Describe the bug**
Spam Scores (e.g. "-12.34") and Spam Score Icons are shown correctly as columns in the table mail view. The Spam Score shown as a button for a mail is also working correctly. Clicking on the button results in an empty view whithout any content.
Therefore one has to open the mail headers to get details.

**Reproduction steps**
Click on the Spam Score button of any mail and the empty view is shown.

**Expected behavior**
The view should contain details about the differents weights and scores set by the mail system.

**Screenshots**
![screenshot-20241007-232945](https://github.com/user-attachments/assets/e7abf9b8-9998-440f-b6b8-4da083fcafba)

**Thunderbird:**
 - OS: Arch Linux
 - Version: 128.3.0-1 (official ArchLinux package)

**Spam Score add-on:**
 - Version: 1.5.0 (installed from GitHub releases)

**Additional context**
Headers starting with `X-Spam`:

```
X-Spamd-Bar: ------
X-Spamd-Result: default: False [-6.82 / 15.00];
	BAYES_HAM(-3.00)[100.00%];
	DWL_DNSWL_MED(-2.00)[python.org:dkim];
	RCVD_DKIM_ARC_DNSWL_MED(-0.50)[];
	DMARC_POLICY_ALLOW_WITH_FAILURES(-0.50)[];
	R_SPF_ALLOW(-0.20)[+mx];
	MAILLIST(-0.20)[mailman];
	RCVD_IN_DNSWL_MED(-0.20)[188.166.95.178:from];
	R_DKIM_ALLOW(-0.20)[python.org:s=200901];
	MIME_GOOD(-0.10)[text/plain];
	MIME_BASE64_TEXT(0.10)[];
	MX_GOOD(-0.01)[];
	HAS_LIST_UNSUB(-0.01)[];
	FORGED_SENDER_MAILLIST(0.00)[];
	RCVD_TLS_LAST(0.00)[];
	RCPT_COUNT_TWO(0.00)[2];
	RCVD_COUNT_THREE(0.00)[3];
	MIME_TRACE(0.00)[0:+];
	REPLYTO_DOM_EQ_TO_DOM(0.00)[];
	RCVD_IN_DNSWL_NONE(0.00)[209.85.128.43:received];
	ARC_NA(0.00)[];
	DKIM_MIXED(0.00)[];
	HAS_REPLYTO(0.00)[python-list@python.org];
	REPLYTO_DOM_EQ_FROM_DOM(0.00)[];
	TO_DN_NONE(0.00)[];
	FROM_NEQ_ENVFROM(0.00)[thomas@python.org,python-announce-list-bounces@python.org];
	FROM_HAS_DN(0.00)[];
	R_DKIM_REJECT(0.00)[python.org:s=200901];
	RCVD_VIA_SMTP_AUTH(0.00)[];
	MISSING_XM_UA(0.00)[];
	DMARC_POLICY_ALLOW(0.00)[python.org,none];
	ASN(0.00)[asn:14061, ipnet:188.166.64.0/18, country:US];
	DKIM_TRACE(0.00)[python.org:+,python.org:-];
	FORGED_RECIPIENTS_MAILLIST(0.00)[]
```

**Comment by alainwolf** [comment]
Me too with Thunderbird 128.3.1esr snap package on Ubuntu 24.04.1 LTS (Gnome 46/Wayland)

**Comment by alainwolf** [comment]
Since the Thunderbird update to 128.4.0esr (64-bit) today, I can see the scores again. :)
