### ISSUE TITLE
Spam Score only shown in Mail, Column show NaN

### ISSUE THREAD

**Issue by hackerscomputer** [friedPotat0/Spam-Scores#9]
Thunderbird 78.5.0 64 bit, Spam Score v 1.1.3 same problem, Spam Score and Report is correctly shown when viewing an email, but it's not shown in the column (show NaN ). The Header is "X-Server3-MailScanner-SpamCheck".
Tryed with open email, restart and repair folder.

**Comment by friedPotat0** [comment]
This is strange. It should work after opening any of these mails and then restarting and repairing the folder. But it seems like that is exactly what you did. Could you please post an example of the corresponding headers of one of your mails (only the MailScanner parts). It seems like the score value itself is not parsed correctly, but the header is correctly recognised.

**Comment by hackerscomputer** [comment]
here

X-Server3-MailScanner-Information: Please contact the ISP for more information
X-Server3-MailScanner-ID: 1kiiMy-000Gj8-Nx
X-Server3-MailScanner: Found to be clean
X-Server3-MailScanner-SpamCheck: non spam, SpamAssassin (not cached,
	punteggio=-2.807, necessario 6, autolearn=not spam, BAYES_50 0.80,
	DKIM_SIGNED 0.10, DKIM_VALID -0.10, DKIM_VALID_AU -0.10,
	DKIM_VALID_EF -0.10, DMARC_PASS -2.00, HTML_IMAGE_ONLY_16 1.09,
	HTML_MESSAGE 0.00, MAILING_LIST_MULTI -1.00, PYZOR_CHECK 0.70,
	SPF_HELO_NONE 0.00, SPF_PASS -0.00, ZZ_META_COUNTRY_OTHER 0.30,
	ZZ_META_NEWSLETTER_NOIT 1.00, ZZ_NEWSLETTER 1.00,
	ZZ_RBL_HOSTKARMA_W -4.50)
X-Server3-MailScanner-From: noreply@github.com
X-Spam-Status: No

**Comment by friedPotat0** [comment]
The problem is the part `punteggio=-2.807`. I didn't know that it is possible that it could be written in any language. Normally a MailScanner header looks like this:
`X-MyCompany-MailScanner-SpamCheck: spam, SpamAssassin (not cached, score=8.609,[...]`

I'm not sure if it is a good idea to manually patch one language after another to support all language possibilities in those headers. Is it possible, that you change the language of these headers in the mail server?

**Comment by maxisvk** [comment]
server side not, maybe from mailscanner v5 repository can get the combo for `score` for all languages? 

`38: score = punteggio`

https://github.com/MailScanner/v5/blob/3e5e4c20d943f5197cfcc3f9d4171a9b3d0acf48/common/usr/share/MailScanner/reports/it/languages.conf

**Comment by friedPotat0** [comment]
Thanks for the link. I will add support for all languages of the MailScanner repository in the next update. I will have a look at it this weekend...

**Comment by friedPotat0** [comment]
Should be working now. I will upload the patch as a new version of the add-on after a few quality checks tomorrow.

If you like to test the new version yourself, you can download the files from the add-mailscanner-languages branch (https://github.com/friedPotat0/Spam-Scores/archive/add-mailscanner-languages.zip) and create a new ZIP file containing all files in the "Spam-Scores-add-mailscanner-languages" folder. Then you can add the file to thunderbird using drag & drop to install the new version.

**Comment by hackerscomputer** [comment]
yes, it works. thanks
